export const HeaderMenu = [
    { id: 1, menu_name: "DELIVERY FEE", link_url: "/delivery-fee" },
    { id: 2, menu_name: "BUSINESS OWNER", link_url: "/retailer" },
    { id: 3, menu_name: "DELIVERY PARTNERS", link_url: "/delivery-partner" },
    { id: 4, menu_name: "ABOUT US", link_url: "/about-us" },
    // { id: 5, menu_name: "BLOGS", link_url: "/blogs" }
]
export const HomePageSection2 = [
    {
        id: 1, img: "./section21.png", heading: "Easy Registration Process", desc: "Both businesses and delivery partners can register by mentioning their names and contact details."
    },
    {
        id: 2, img: "./section22.png", heading: "Order Delivery", desc: "While businesses enjoy low-cost and on-time delivery services, delivery partners earn more with us."
    },
    {
        id: 3, img: "./section23.png", heading: "Delivery updates", desc: "We’ll provide businesses with updates such as order booking, order pick-up, order delivery, etc."
    }
]
export const keyFeatures = [
    {
        id: 1, img: "./key_features1.png", heading: "Safe & On-time Delivery", desc: "Our trained delivery staff delivers shipments to customers safely and on time."
    },
    {
        id: 2, img: "./key_features2.png", heading: "Hi-tech Delivery Management", desc: "We rely on advanced logistic technologies to ensure seamless product deliveries, making both businesses and their customers happy."
    },
    {
        id: 3, img: "./key_features3.png", heading: "Growing Delivery Network", desc: "Our delivery network is expanding at a rapid pace. Currently, we are serving in 35 cities across India."
    },
    {
        id: 4, img: "./key_features3.png", heading: "Increased Earnings for Delivery Partners", desc: "Handover’s Delivery Partners can choose multiple locations to get maximum orders, which will help them earn more."
    }

]

export const whyHandover = [
    {
        id: 1, heading: "The Freedom to Order Anytime", desc: "handover allows you to place orders with it anytime."
    },
    {
        id: 2, heading: "No Need to Call Anyone for Deliveries", desc: "The hi-tech delivery management system ensures a seamless process from order creation to order delivery, eliminating the need for businesses to call anyone."
    },
    {
        id: 3, heading: "Trained Staff for Delivery Services", desc: "Handover’s trained delivery staff can safely deliver temperature-sensitive and fragile products."
    },
    {
        id: 4, heading: "Our Presence", desc: "We are currently delivering in 35 cities across India, and will soon be available in many other cities."
    }
]

export const AboutUsCardItemData = [
    {
        id: 1, img_url: "./about_us1.png",
        heading: "Our Purpose",
        desc: "Businesses are doing well but haven’t been able to control their delivery cost. handover looks to reduce their delivery expenses and allow them to earn more business. Businesses can deliver stuff to far distant locations in the city with handover."
    },
    {
        id: 2,
        img_url: "./about_us2.png",
        heading: "Our Vision",
        desc: "We want to make businesses, handover’s Delivery Partners and the end users happy with our delivery services. And we are confident of maintaining so with our unwavering commitment, trained delivery staff, smart technology, and much more."
    },
    {
        id: 3,
        img_url: "./about_us3.png",
        heading: "Our Positioning",
        desc: "handover has already gained a significant foothold in India’s logistics space, courtesy of hi-tech delivery management, delivery partners, etc. With a strong presence across 35 cities in India, we have been successfully catering to various logistics demands raised by businesses."
    }
]

export const RetailersData = [
    {
        id: 1,
        img_url: "./delivery_partner_1.png",
        heading: "आपके Customer रहेंगे हमारी On-time Delivery से खुश",
        description: "handover के Delivery Partners हैं Time के पक्के। वह आएंगे आपकी दुकान पर, सामान उठाएंगे और पंहुचा देंगे उसे आपके Customers के पास Time पर। On-time Delivery से आपके Customers रहेंगे आपसे खुश।",
        link_url: ""
    },
    {
        id: 2,
        img_url: "./delivery_partner_2.png",
        heading: "फिजूल Delivery खर्चों पर लगाए BREAK",
        description: "भले ही आप अपनी मुस्कुराहट से अपने दर्द को छिपा रहे हो, लेकिन हम जानते हैं आप को कुछ दिक्कतें तो हैं। आपकी Salary वाली Delivery Force आप पर बोझ बन रही हैं। Delivery Time पर हो ना हो, Time पर Salary ज़रूर ले रहे हैं। handover दे रहा हैं आपको Delivery Force सिर्फ Delivery Basis पर। इससे आप फिजूल खर्चों से बच सकेंगे।",
        link_url: ""
    },
    {
        id: 3,
        img_url: "./delivery_partner_3.png",
        heading: "हम करेंगे Delivery, आप बढ़ाए व्यापार",
        description: "Delivery हम करेंगे On Time, देंगे आपको पल पल की Delivery Updates आपके दिए गए Mobile Number पर। इससे आप अपना पूरा  ध्यान व्यापार को बढ़ाने में लगा सकेंगे।।",
        link_url: ""
    },
    {
        id: 4,
        img_url: "./delivery_partner_4.png",
        heading: "ज़्यादा से ज़्यादा Customers को आप कर पाएंगे Entertain",
        description: "क्योंकि हमारे Delivery Partners हैं चप्पे चप्पे पर, आप अपनी Reach को काफी ज़्यादा बढ़ा सकते हैं हम से जुड़ कर। ज़्यादा Customers मतलब ज़्यादा Business।।",
        link_url: ""
    },
    {
        id: 5,
        img_url: "./delivery_partner_5.png",
        heading: "हमारी Delivery Workforce है तैयार",
        description: "आप हैं हमारे लिए ख़ास। आपको कोई दिक्कतें ना हो इसलिए हमने आपके लिए  Delivery Workforce तैयार तैयार रखी हैं।",
        link_url: ""
    },
    {
        id: 6,
        img_url: "./delivery_partner_6.png",
        heading: "Delivery Service जल्द ही Start हो जाएगा",
        description: "handover के साथ आप तुरंत अपने Customers को Deliver कर पाएंगे। आप handover App या हमारे Website पर आकर Register कर सकते हैं। Registration करने के लिए आपको अपना नाम, Mobile Number, Email ID Mention करना होगा Form पर।  Once Registration Done, Delivery is On!",
        link_url: ""
    }
]


export const DeliveryPartnersData = [
    {
        id: 1,
        img_url: "./delivery_partner_1.png",
        heading: "अच्छी कमाई करने का मौका",
        description: "डेढ़ सारे Orders से आपके पास कमाने के ज़्यादा मौके होंगे। जितनी Delivery उतनी कमाई। आप खुद के Boss हैं",
        link_url: ""
    },
    {
        id: 2,
        img_url: "./delivery_partner_2.png",
        heading: "इस Freedom से आप बेहतर Delivery Performance दे पाएंगे",
        description: "आपका Delivery सफर रहने वाला हैं 100% Interesting आप बीच बीच में Reels और Videos का भी लुत्फ़ उठा सकते हैं. मतलब काम और Entertainment साथ साथ।",
        link_url: ""
    },
    {
        id: 3,
        img_url: "./delivery_partner_3.png",
        heading: "Delivery होगी City के अंदर ही",
        description: "हमे आपका ख्याल हैं। इसलिए हम आपको आपके शहर के ही Delivery Orders देंगे।",
        link_url: ""
    },
    {
        id: 4,
        img_url: "./delivery_partner_4.png",
        heading: "आप पा सकते हैं अच्छे Customer Rating",
        description: "अच्छी Delivery Service देकर आप पा सकते हैं अच्छे Customers Rating जो आपके Career के लिए होगा फायदेमंद।",
        link_url: ""
    },
    {
        id: 5,
        img_url: "./delivery_partner_5.png",
        heading: "आप Family Life का भी लुत्फ़ उठा सकते हैं",
        description: "Hyperlocal Delivery से आपके पास Family और Friends दोनों के साथ Quality Time Spend करने का मौका रहेगा।",
        link_url: ""
    },
    {
        id: 6,
        img_url: "./delivery_partner_6.png",
        heading: "Delivery Service जल्द ही Start हो जाएगा",
        description: "Hyperlocal Delivery से आपके पास Family और Friends दोनों के साथ Quality Time Spend करने का मौका रहेगा।",
        link_url: ""
    }
]

export const FAQ = [
    {
        id: 1,
        heading: 'What Special About handover?',
        description: ' Yes, it is! handover has made the entire delivery system cost-efficient and transparent by reviving interactions between businesses and their customers.'
    },
    {
        id: 2,
        heading: 'How Can Businesses Register with handover?',
        description: 'Businesses can register with handover on its official website and app.'
    },
    {
        id: 3,
        heading: 'What is the Registration Process for Businesses with handover?',
        description: '<b>On Website</b> <br />Click on the ‘Retailers’ icon<br />Choose ‘Retailer’ from the drop-down<br />Mention your name, email address and mobile number, and click on ‘Send Message’<br />We will verify the details before registering your business for delivery services<br /><br /><b>On App</b><br />Download the handover Business App from the Google Play Store<br />After giving location permission access and doing mobile number authentication, enter your name, the business name, the type of business, etc.<br />After successful verification of these details, we will get you registered for delivery services.'
    },
    {
        id: 4,
        heading: 'Do I Need to Recharge the Wallet for Delivery Services?',
        description: 'Yes! Businesses must recharge their wallets for uninterrupted delivery services. Delivery charges are automatically deducted from the wallet.'
    },
    {
        id: 5,
        heading: 'How Do I Know My Wallet Recharge Status?',
        description: ' Visit the ‘Recharge Wallet’ section on the handover Business App to know the balance left for deliveries. '
    }
]

export const Location = [
    { id: 1, location_name: "patna", link_url: "./patna.png" },
    { id: 2, location_name: "muzaffarpur", link_url: "./muzaffarpur.png" },
    { id: 3, location_name: "chandigarh", link_url: "./chandigarh.png" },
    { id: 4, location_name: "ghaziabad", link_url: "./ghaziabad.png" },
    { id: 5, location_name: "delhi-ncr", link_url: "./delhi-ncr.png" },
    { id: 6, location_name: "karnal", link_url: "./karnal.png" },
    { id: 7, location_name: "ranchi", link_url: "./ranchi.png" },
    { id: 8, location_name: "jamshedpur", link_url: "./jamshedpur.png" },
    { id: 9, location_name: "bangalore", link_url: "./bangalore.png" },
    { id: 10, location_name: "hubli", link_url: "./hubli.png" },
    { id: 11, location_name: "indore", link_url: "./indore.png" },
    { id: 12, location_name: "ujjain", link_url: "./ujjain.png" },
    { id: 13, location_name: "bhopal", link_url: "./bhopal.png" },
    { id: 14, location_name: "thane", link_url: "./thane.png" },
    { id: 15, location_name: "mumbai", link_url: "./mumbai.png" },
    { id: 16, location_name: "navi-mumbai", link_url: "./navi-mumbai.png" },
    { id: 17, location_name: "nashik", link_url: "./nashik.png" },
    { id: 18, location_name: "aurangabad", link_url: "./aurangabad.png" },
    { id: 19, location_name: "pune", link_url: "./pune.png" },
    { id: 20, location_name: "cuttack", link_url: "./cuttack.png" },
    { id: 21, location_name: "puri", link_url: "./puri.png" },
    { id: 22, location_name: "ludhiana", link_url: "./ludhiana.png" },
    { id: 23, location_name: "jaipur", link_url: "./jaipur.png" },
    { id: 24, location_name: "hyderabad", link_url: "./hyderabad.png" },
    { id: 25, location_name: "lucknow", link_url: "./lucknow.png" },
    { id: 26, location_name: "kanpur", link_url: "./kanpur.png" },
    { id: 27, location_name: "allahabad", link_url: "./allahabad.png" },
    { id: 28, location_name: "varanasi", link_url: "./varanasi.png" },
    { id: 29, location_name: "midnapore", link_url: "./midnapore.png" },
    { id: 30, location_name: "kharagpur", link_url: "/kharagpur.png" },
    { id: 31, location_name: "noida", link_url: "./noida.png" },

]



export const LocationInfoData = [
    { location: "patna",map_url: "https://www.google.com/maps/place/Patna,+Bihar/@25.601933,85.0417899,11z/data=!4m6!3m5!1s0x39f29937c52d4f05:0x831a0e05f607b270!8m2!3d25.5940947!4d85.1375645!16zL20vMDI3d3Zi?entry=ttu", location_name: "Delivery Services in Patna", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Patna.', des1: 'Many shops, restaurants, food stores and other businesses look for people who could deliver stuff ranging from food to laptops in Patna. This is despite their own delivery force. The reason - businesses often hire delivery executives on a fixed salary basis. However, they often deliver late. So, both cost and delivery service wise, businesses want to get better.', des2: 'With Handover, businesses can be assured of the timely delivery of orders to their customers in Patna. Whereas Handover Champs can earn on the deliveries they make. These champs can do food delivery jobs, grocery delivery jobs, milk delivery jobs and other delivery work in Patna.', heading2: 'Exploring Patna', subheading2: 'Let’s Check Out Patna and Its Specialties', des3: 'Very rarely one comes across a city whose name has been changed multiple times. Patna, the capital city of Bihar, previously had names of Pataligram, Kusumpur, Patliputra, Azimabad, etc. The city boasts of several emperors who made it their capital. Chandragupta Maurya and Samudragupta are those established names. Presently, the city has many schools, government offices, amusement centres, food corners and cinema halls. Simple living style and delicious foods make this city a great place to live in.', population: ' 20 lakh (approx.)', popularsites: 'Takht Sri Patna Sahib, Gandhi Maidan, Golghar, Patna Planetarium' },
    { location: "muzaffarpur",map_url: "https://www.google.com/maps/place/Muzaffarpur,+Bihar/@26.1280002,85.2825276,12z/data=!4m6!3m5!1s0x39ed10e8a3175529:0x7c2d919680f759d!8m2!3d26.1196607!4d85.390982!16zL20vMDVwbmht?entry=ttu", location_name: "Delivery Services in Muzaffarpur", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Muzaffarpur.', des1: 'Looking for people who can deliver goods to the customers on time in Muzaffarpur? Or are searching for delivery jobs in Muzaffarpur? Handover welcomes both of you. We ensure food delivery jobs, grocery delivery jobs and related work in the city.', des2: 'As a shopkeeper, you can now feel free to entertain maximum orders to boost your sales. Handover Champs are there to deliver across Muzaffarpur. For us, the size of the business does not matter. Small or big business, we support all through our delivery services. Join Handover, take its services and share your views on the same', heading2: 'Exploring Muzaffarpur', subheading2: 'Let’s Check Out Muzaffarpur and Its Specialties', des3: 'Muzaffarpur, a popular city in the state of Bihar, is known for its Litchis. Once it was the part of glorious civilisation of ancient India and has now become the economic hub of modern Bihar. Muzaffarpur has been the 3rd most populous district of Bihar. Moreover, the city has been ruled by different dynasties till independence. But the modern Muzaffarpur city was established by the British empire in 1875 and named after its revenue officer Muzaffar Khan. There are numerous historical places in Muzaffarpur where visitors come every year.', population: '487000 (approx.)', popularsites: ' Ashoka Pillar, Litchi Gardens, Ramna Devi Mandir, etc.' },
    { location: "chandigarh",map_url: "https://www.google.com/maps/place/Chandigarh/@30.723659,76.719045,11z/data=!4m6!3m5!1s0x390fed0be66ec96b:0xa5ff67f9527319fe!8m2!3d30.7333148!4d76.7794179!16zL20vMDFmMXE4?entry=ttu", location_name: "Delivery Services in Chandigarh", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Chandigarh.', des1: 'Chandigarh is considered the education hub across Punjab, Haryana and Himachal Pradesh, and South-East Asia. So many students come here to pursue their studies, and unfortunately, some of them cannot meet their needs due to a lack of a job. Now, you dont need to worry anymore, because Handover has a job vacancy for food delivery, grocery delivery and many other such jobs.', des2: 'As retailers, you must also be happy that we are in your city to boost your sales. We help businesses with adequate manpower support for deliveries. Our delivery executives deliver maximum orders to increase your business and get paid on a pay per delivery model, eliminating the fixed salary burden for you.', heading2: 'Exploring Chandigarh', subheading2: 'Let’s Check Out Chandigarh and Its Specialties', des3: 'Chandigarh is the first modern planned city of India designed by the French architect Le Corbusier. Despite being the capital of two states Punjab and Haryana, Chandigarh region does not fall under the jurisdiction of any of them and is ruled by the Central Government as it is classified as union territory. However, the city has been named after the mother goddess of power, Chandi whose temple Chandimandu is situated in the city. Besides, it was the dream city of India’s first Prime Minister Jawahar Lal Nehru. The literacy rate of the city is 97% which is appreciated across the country. When we talk about food, Chandigarh is recognised for its various delicious cuisines – Chole-Bhature, Sarso ka saag served with lots of white butter, Lussi, etc.', population: '13.25 lakh (approx)', popularsites: 'The Rock Garden of Chandigarh, Chandigarh Rose Garden, Mahendra Chaudhary Zoological park, Punjab University.' },
    { location: "ghaziabad",map_url: "https://www.google.com/maps/place/Ghaziabad,+Uttar+Pradesh/@28.6722299,77.3007031,11z/data=!4m6!3m5!1s0x390cf1bb41c50fdf:0xe6f06fd26a7798ba!8m2!3d28.6691565!4d77.4537578!16zL20vMDZkbG0x?entry=ttu", location_name: "Delivery Services in Ghaziabad & Delivery Jobs in Ghaziabad", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Ghaziabad', des1: 'Handover is looking for people who can deliver the products from retailers to customers on time. This is a great opportunity for those searching for food delivery jobs in in Ghaziabad, grocery delivery jobs in Ghaziabad and other delivery jobs in Ghaziabad for their livelihood', des2: 'Retailers around Ghaziabad city can rely on us to serve maximum delivery orders every day. Handover has delivery executives across Ghaziabad.', heading2: 'Exploring Ghaziabad', subheading2: 'Let’s Check Out Ghaziabad and Its Specialties', des3: 'Ghaziabad city is situated near the Indian national capital Delhi, and comes in the state  of Uttar Pradesh. Once, the city was part of the Meerut province but in 1976, it got the status of a separate district. Now, Ghaziabad has become more progressive and prosperous due to its strategic location. In fact, the city stands in the list of few industrial hubs of the country. However, the history of the city could be traced back to 2500 BC according to some excavation reports. Therefore, several dynasties and rulers had administered the city – Maurya, Gupta, Mughal and the British, etc. Furthermore, during the 1857 mutiny against the British, Ghaziabad was at the forefront revolting against the colonial power. So many British soldiers and Indian freedom fighters’ graves can be seen around the city.', population: '16.5 lakh (approx)', popularsites: 'Shipra Mall, Drizzling Land – Water and Amusement Park, City Forest etc.' },
    { location: "noida",map_url: "https://www.google.com/maps/place/Noida,+Uttar+Pradesh/@28.358903,77.2425293,10.7z/data=!4m6!3m5!1s0x390ce5a43173357b:0x37ffce30c87cc03f!8m2!3d28.5355161!4d77.3910265!16zL20vMDN3dHow?entry=ttu", location_name: "Delivery Services in Noida", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Noida.', des1: 'As Noida is the hub of IT firms and multinational companies, there are lots of job opportunities here. In addition, Handover is giving motorcycle delivery jobs to those seeking grocery delivery jobs, food delivery jobs and related work. So if you want to earn money through these jobs, contact us ASAP.', des2: 'Retailers may be skipping entertaining delivery orders of customers staying far away from their shops.  As a result, you miss expanding your business. To fix your problems, Handover gives you the appropriate delivery support. You get people who would pick up goods from your shop and deliver it to your customers on time. The best part is that you don’t need to keep your delivery force on a salary basis. These executives will earn based on the deliveries they do.', heading2: 'Exploring Noida', subheading2: 'Let’s Check Out Noida and Its Specialties', des3: 'Noida has always been the hub for trade, commerce and education due to its proximity to Delhi. In 1976, the Noida urbanization initiative foundation was led under the management and administration of the New Okhla Industrial Development Authority (NOIDA). Now Noida is considered one of the best cities of the country with well developed infrastructure and transportation systems. Besides, the city provides numerous job opportunities to people across disciplines and companies.', population: ' 8.77 lakh (approx)', popularsites: 'Okhla Bird Sanctuary, Botanic Garden, World of Wonders, National Zoological Park, etc.' },
    { location: "delhi-ncr",map_url: "https://www.google.com/maps/place/Delhi/@28.6442873,76.7635563,10z/data=!3m1!4b1!4m6!3m5!1s0x390cfd5b347eb62d:0x37205b715389640!8m2!3d28.7040592!4d77.1024902!16zL20vMDlmMDc?entry=ttu", location_name: "Delivery Services in Delhi- NCR", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Delhi.', des1: 'Searching for people who could deliver orders to your customers on time in Delhi-NCR? Or are you searching for food delivery jobs, grocery delivery jobs in the city? We welcome all of you at Handover!', des2: 'As a business owner, you can continue entertaining orders from all over Delhi-NCR and rely on us to get them delivered to your customers. Best part – we help you eliminate the fixed cost of your own delivery force. You will also get real-time delivery status updates from us. We already provide delivery services to numerous business enterprises in the city. So, hand over your delivery concerns and focus on growing your business as your peers.Whereas Handover Champs can deliver, earn and be financially independent. The earnings will depend on the number of deliveries they make. So champs, keep pushing and help us bridge the city’s delivery gaps!', heading2: 'Exploring Delhi', subheading2: 'Let’s Check Out Delhi and Its Specialties', des3: 'The capital city of Delhi has glorious sights to witness. These include ancient architecture, commercial buildings, the Indian Institute of Technology (IIT), the National School of Drama (NSD), etc. And if you are a foodie, you will love being here! You can visit Paranthe Wali Gali (Chandni Chowk), Khan Market, Hudson Lane, Pandara Road, Connaught Place, etc. You can even get discounts, cashback and other catchy deals when dining here. Other attractions of the city include flyovers, amusement parks, nightclubs, metros, etc. Also, the city is home to people from various backgrounds. People from all over India come here to earn their livelihood. In short, Delhi welcomes all!', population: '3.2 Crores (Approx.)', popularsites: 'Lal Quila, Qutub Minar, Lotus Temple, Akshardham Temple, India Gate' },
    { location: "karnal",map_url: "https://www.google.com/maps/place/Karnal,+Haryana/@29.6853134,76.9472322,13z/data=!3m1!4b1!4m6!3m5!1s0x390e701851e03e97:0xf84aa8b9e1cc7607!8m2!3d29.6856929!4d76.9904825!16zL20vMDNmdDls?entry=ttu", location_name: "Delivery Services in Karnal", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Karnal.', des1: 'Handover is looking for people who could do bike food delivery jobs, grocery delivery jobs and related work in karnal. You can earn by delivering goods from retailers to customers. You just need to contact us for delivery jobs in Karnal.', des2: 'And if you are a retailer wanting to boost your sales with increased deliveries, Handover is there for you! It helps you maximise your sales in Karnal. Handover executives are ready to deliver your items to customers across Karnal. The best part – they will earn as per their deliveries. So, keep entertaining orders to boost your sales with Handover. Besides, do share your feedback with us for the delivery services. It will help us serve you even better', heading2: 'Exploring Karnal', subheading2: 'Let’s Check Out Karnal and Its Specialties', des3: 'Karnal city is located in the Indian state of Haryana and also known as the rice bowl of India. The name is believed to be given after the name of Karna, a warrior in the ancient epic of Mahabharta. More than 40% of the country’s agricultural implements and its parts are manufactured here. The region is famous for being the trade centre of grains, salt, metal, cotton, etc. Apart from these, the city has been ruled by several dynasties throughout history but came into the light in 1739 when Nadir Shah of Iran defeated Mughal emperor Mohammad Shah and captured the region.', population: '4.37 lakh (approx)', popularsites: 'Karnal lake, Kalander Shah’s Tomb, Cantonment Church Tower, Chhachhrauli Fort, etc.' },
    { location: "panipat",map_url: "https://www.google.com/maps/place/Panipat,+Haryana/@29.3964854,76.8817191,12z/data=!3m1!4b1!4m6!3m5!1s0x390dda457afbe651:0x41d3f6feacaa74d4!8m2!3d29.3909464!4d76.9635023!16zL20vMDQyZGh0?entry=ttu", location_name: "Delivery Services in Panipat", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Panipat', des1: 'Panipat is home to textile, carpet, handloom weaving, and many more businesses. Handover helps these businesses flourish with its on-demand delivery services in Panipat. It starts by receiving orders from shops, restaurants, textile stores and various other businesses in Panipat. It then sends dedicated delivery executives to pick up the orders at respective business outlets. These executives pick the item and deliver the same to customers on time. Some locations where Handover operates in Panipat include Model Town, Fatehpuri Chowk, Sukhdev Nagar, Lal Batti Market, Sanjay Chowk, Sector -11, Huda, etc.', des2: 'We also care for our delivery executives who constantly roam around to deliver across various places in Panipat. They earn good for delivering orders successfully. So anyone who is passionate about delivery jobs in Panipat can join Handover. Our services includes food delivery, grocery delivery and more.', heading2: 'Exploring Panipat', subheading2: 'Let’s Check Out Panipat and Its Specialties', des3: 'Panipat  is a historic city in Haryana, India. The city is known as “City of Weavers” and “Textile City”. One more name is given to the city – “cast-off capital” – as it is  the global centre for recycling textiles.Panipat has numerous manufacturing units of wool, cotton, saltpetre refining, glass, electrical appliances, and other products.Historically speaking, Panipat witnessed three battles that led to the creation of the Mughal Empire in India.', population: '5.85 Lakh (approx)', popularsites: 'Panipat Museum, Kabuli Bagh Masjid, Ibrahim Lodhi Tomb, Panipat Battle Field Memorial, etc.' },
    { location: "ranchi",map_url: "https://www.google.com/maps/place/Ranchi,+Jharkhand/@23.3434338,85.156513,11z/data=!4m6!3m5!1s0x39f4e104aa5db7dd:0xdc09d49d6899f43e!8m2!3d23.3440997!4d85.309562!16zL20vMDF0dHQ2?entry=ttu", location_name: "Delivery Services in Ranchi", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Ranchi.', des1: 'Many youngsters in Ranchi may be looking for grocery delivery jobs and related work. At the same time, many businesses want to cut down their delivery cost. Handover welcomes all! Those looking for delivery jobs can earn on the deliveries they make.', des2: 'Whereas as business owners, you would no longer need to keep delivery executives on a monthly salary. You can thus enjoy lots of savings. Take our services and give us your feedback. We will work on the same', heading2: 'Exploring Ranchi', subheading2: 'Let’s Check Out Ranchi and Its Specialties', des3: 'In 2000, Ranchi was made the capital of the Indian state of Jharkhand. Prior to this, Jharkhand was an integral part of Bihar. But due to political mess up, it became a state in 2000. Besides, Ranchi has witnessed numerous political upheaval within its territory throughout the history stretching from Maurya, Gupta, Mughal to British empire. During the British reign, several anti-British protests began from this very region and the most popular ‘Sardari Agitation’ was led by Birsa Munda, a socio-religious revolutionary who denied paying money to cruel british. These were the glorious past of the city. But now, Ranchi cannot be quoted without mentioning the legendary former Indian cricket team Captain Mahendra Singh Dhoni who comes from this city.', population: '10.7 Lakh (approx)', popularsites: 'Birsa Zoological park, JSCA International stadium, Tagore Hill, Ranchi Lake, etc.' },
    { location: "jamshedpur",map_url: "https://www.google.com/maps/place/Jamshedpur,+Jharkhand/@12.9542802,77.4661253,11z/data=!4m2!3m1!1s0x39f5e31989f0e2b5:0xeeec8e81ce9b344?entry=ttu", location_name: "Delivery Services in Jamshedpur", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Jamshedpur.', des1: 'Handover is in search of people wanting to be self-reliant. It has created great opportunities for those wanting milk delivery jobs, grocery delivery jobs, food delivery jobs and alike in Jamshedpur.', des2: 'For retailers, it is the great time to enhance their sales. Handover is ready to assist you by providing delivery executives who can deliver your products to customers on time. The best part – you no longer need to keep people for delivery on a fixed cost basis. These executives will take money basis their deliveries. Think about joining Handover and using its delivery services. We will also appreciate it if you give us your feedback about the delivery services.', heading2: 'Exploring Jamshedpur', subheading2: 'Let’s Check Out Jamshedpur and Its Specialties', des3: 'Jamshedpur is considered the first planned industrial city of India. Previously, the city was known as Sakchi but in 1919, Lord Chelmford renamed it as Jamshedpur honouring Jamshedji Nusserwanji Tata for his contribution in World War 1.Jamshedpur has an abundance of Iron, Coal, Limestone and Water. So due to the rich amounts of natural resources in the city, the first steel plant was established here. Apart from these, in 2020, Jamshedpur was ranked as the cleanest city of India by Swach Survekshan.', population: '6.31 Lakh (approx)', popularsites: 'Dalma Wildlife Sanctuary, Jubilee Park, Tata Steel Zoological Park, etc.' },
    { location: "bangalore",map_url: "https://www.google.com/maps/place/Bengaluru,+Karnataka/@12.9542802,77.4661253,11z/data=!3m1!4b1!4m6!3m5!1s0x3bae1670c9b44e6d:0xf8dfc3e8517e4fe0!8m2!3d12.9715987!4d77.5945627!16zL20vMDljMTc?entry=ttu", location_name: "Delivery Services in Bangalore", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Bangalore.', des1: 'Bangalore being the Silicon Valley of India attracts people from all over India seeking IT jobs. But not all of you may be IT graduates. So, in case you are looking for food delivery jobs, grocery delivery jobs and other delivery jobs in Bangalore, Handover is there to support you. You can be our next delivery champ and can earn money by picking goods from retailers and delivering them to their customers.', des2: 'Whereas as business owners, you may be feeling a bit burdened by keeping your delivery executives on a fixed cost basis. Handover’s delivery model benefits you too. We provide you with delivery champs who get paid based on the deliveries they do. Overall, this mechanism can boost your profits. Also, give us your feedback on Handover services. We will appreciate the same.', heading2: 'Exploring Bangalore', subheading2: 'Let’s Check Out Bangalore and Its Specialties', des3: 'Bangalore was officially renamed Bengaluru in 2006 and is the capital of Karnataka. The city has been given several nicknames, including Silicon Valley of India, IT Capital of India and Garden city, etc. Let us go back a little. The city got special attention from the government just after independence, which led to its rapid development in several sectors like education, real estate, finance, etc. But after the Liberalisation, Privatization and Globalization (LPG) policies adopted by the central government in 1991, Bangalore has experienced rapid progress in the information and communications and technology (ICT) sector, resulting in national and global fame for the city.', population: '11.64 lakh (approx.)', popularsites: 'IIT Bangalore, Tipu Sultan’s Summer Palace, National Gallery of Modern Art, Nandi Hills, etc.' },
    { location: "hubli",map_url: "https://www.google.com/maps/place/Hubballi,+Karnataka/@15.3577388,75.0267458,12z/data=!3m1!4b1!4m6!3m5!1s0x3bb8d6d3a2090b17:0xae803e207113397!8m2!3d15.3647083!4d75.1239547!16zL20vMDE2YmY1?entry=ttu", location_name: "Delivery Services in Hubli", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Hubli.', des1: 'If you are looking for food delivery jobs, grocery delivery jobs & other delivery jobs in Hubli city, connect with Handover today! We are providing job opportunities in your city so that you can earn by delivering goods. Handover will ensure you pick up the products from retailers and deliver them to their customers.', des2: 'As retailers, you can get rid from paying fixed salaries to your delivery executives which will surely reduce your burden. Handover provides you executives who will pick up goods from you and deliver them to your customers. These executives receive money on the basis of every delivery they do. So, it motivates them to do maximum delivery in a day, enhancing your sales. But do get back to us with your feedback on our delivery services. We will appreciate the same!', heading2: 'Exploring Hubli', subheading2: 'Let’s Check Out Hubli and Its Specialties', des3: 'Hubli is the second largest city of Karnataka and is also known as ‘Chota Mumbai’ due to its large commercial activities. The city has witnessed rise and fall of several dynasties who ruled over it. Besides, Hubli has always been the centre for producing plenty of commodities such as peanuts, cotton, Iron, etc. But after the British took control over the city, its commercial activities flourished to a large extent due to the railway construction. Furthermore, several small and big industries were set up in the city resulting in the employment of many people back in the 19th century. Nowadays, apart from industrial business, agriculture farming is another hope of people which helps in increasing the economy and lifestyle of the city.', population: '12.9 lakh (approx.)', popularsites: ' Nrupatunga Betta, Unkal Lake, Glass House Garden,Water Park, etc.' },
    { location: "indore",map_url: "https://www.google.com/maps/place/Indore,+Madhya+Pradesh/@22.724205,75.6990366,11z/data=!3m1!4b1!4m6!3m5!1s0x3962fcad1b410ddb:0x96ec4da356240f4!8m2!3d22.7195687!4d75.8577258!16zL20vMDFfeXZ5?entry=ttu", location_name: "Delivery Services in Indore", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Indore.', des1: 'Handover is looking for people who want food delivery jobs, grocery delivery jobs and other delivery jobs in Indore. We are offering delivery job opportunities for the people of Indore. Register with Handover, pick up the products from retailers and deliver them to their customers.', des2: 'As retailers, paying fixed salaries to your delivery executive every month must be taxing for you. You may have tried moving away from this fixed payment concept but could not do so. Therefore, we have come with an idea which may fascinate you. Handover provides delivery executives to shopkeepers who will pick up the goods from your shop and deliver them to your customers. Delivery champs earn the money based on the delivery they do. Furthermore, it motivates them to do maximum deliveries a day and enhance your sales. Do get back to us with your feedback on our delivery services. We will appreciate the same!', heading2: 'Exploring Indore', subheading2: 'Let’s Check Out Indore and Its Specialties', des3: 'Indore has been in the news for glorious reasons. According to Swachh Survekshan Report 2022, the city is considered the cleanest city of India for six consecutive times. Besides, Indore is known as the education hub of Madhya Pradesh due to prestigious IIT and IIM. The city has been manufacturing several products such as textiles, tile, cement, chemicals, tents, furniture, sports goods, etc. Indore was founded in 1715 by local trade owners on the Narmada river valley route and now it has become the most populous city of state. There are many architectural monuments built in the city, illustrating the glory of past empires.', population: '27 lakh (approx.)', popularsites: 'Rajwada Palace, Annapurna Temple, Lal Bagh Palace, etc.' },
    { location: "ujjain",map_url: "https://www.google.com/maps/place/Ujjain,+Madhya+Pradesh/@23.1690722,75.7560206,13z/data=!3m1!4b1!4m6!3m5!1s0x39637469de00ff23:0x7f82abdf7899d412!8m2!3d23.1764665!4d75.7885163!16zL20vMDNuNjcw?entry=ttu", location_name: "Delivery Services in Ujjain", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Ujjain.', des1: 'If you are looking for food delivery jobs, grocery delivery jobs and other delivery jobs in Ujjain, connect with Handover ASAP. We are providing job opportunities to the people of Ujjain city so that you can earn your livelihood just by working with us.', des2: 'As retailers, if you are frustrated by paying a fixed salary to your delivery executive every month, you can reduce your burden by collaborating with Handover. We provide you with delivery executives who will pick up the orders from you and deliver them to your customers purely on a delivery basis. No fixed cost burden. We’re waiting to serve you. Register with us today and get those delivery executives for your customers.', heading2: 'Exploring Ujjain', subheading2: 'Let’s Check Out Ujjain and Its Specialties', des3: 'It is said that the name of Ujjain is mentioned in various Hindu sacred scriptures such as Puranas and Upanishad by its old names Avantika, Ujjayani, Kanishka. This very city is one of the seven Hindu pilgrimage centers famous for organising Kumbh Mela every 12 years. These all illustrate the importance of the city, its relevance in ancient times and today. In the past, it is believed that Ujjain was the political centre of Central India around 600 BCE during the control of the Avanti kingdom. Besides, several dynasties had ruled the region across centuries. Nowadays, Ujjain is known for its historical temples where people come from different parts of India and around the world. Prime Minister Narendra Modi had even included Ujjain as one of the hundred cities to be developed under the ‘Smart City’ mission.', population: '7 lakh (approx.)', popularsites: 'Mahakaleshwar Jyotirlinga Temple, Mahakal Lok Corridor, ISKCON Temple, etc' },
    { location: "bhopal",map_url: "https://www.google.com/maps/place/Bhopal,+Madhya+Pradesh/@23.1996395,77.2410782,11z/data=!3m1!4b1!4m6!3m5!1s0x397c428f8fd68fbd:0x2155716d572d4f8!8m2!3d23.2599333!4d77.412615!16zL20vMGN3NTE?entry=ttu", location_name: "Delivery Services in Bhopal", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Bhopal.', des1: 'If you are looking for food delivery jobs, grocery delivery jobs and other delivery jobs in Bhopal, Handover gives you that opportunity. Connect with us and start delivering and earning. Numerous business enterprises look for people who could deliver products to their customers. Demand for delivery jobs remains high in Bhopal.', des2: 'As retailers, you must be annoyed paying a fixed salary to your delivery executives. So Handover has a good idea for you! We provide businesses with people who pick up the items and deliver them to your customers. You may wonder, what’s the difference? The difference is that these executives earn based on their deliveries. No hassle of fixed payments! Let’s join us, use our services, give your feedback, and allow us to serve you better each time.', heading2: 'Exploring Bhopal', subheading2: 'Let’s Check Out Bhopal and Its Specialties', des3: 'Bhopal is the capital of Madhya Pradesh, and also known as the city of lakes. The history of Bhopal has been fascinating with numerous rulers administering the city. It is said that the modern day Bhopal was established by Dost Mohammed Khan, an Afghan commander, under the administration of Mughal Emperor Aurangzeb. Furthermore, In the 19th century, the city experienced a series of social and cultural changes in administration during the time of the then queen Qudasiya Begum. But today, Bhopal stands in the forefront, having the industries of numerous products such as cotton, flour milling, cloth weaving, painting, transformers, traction motors, sporting goods, and heavy electrical equipment.', population: '17.9 lakh (approx.)', popularsites: 'Moti Masjid, Upper Lake, Sanchi Stupa, Birla Museum, etc.' },
    { location: "thane",map_url: "https://www.google.com/maps/place/Thane,+Maharashtra/@19.2140356,72.9190582,12z/data=!3m1!4b1!4m6!3m5!1s0x3be7b8fcfe76fd59:0xcf367d85f7c50283!8m2!3d19.2183307!4d72.9780897!16zL20vMDE2bXA5?entry=ttu", location_name: "Delivery Services in Thane", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Thane.', des1: 'If you are searching for food delivery jobs, grocery delivery jobs and other delivery jobs in Thane, look no further than Handover. This job is open to even those who don’t have any prior work experience. Register with us, do some roaming and feel good with money in your pocket. The job description is simple! Accept delivery orders from businesses, pick the stuff from shops and other business outlets, and deliver them to the customers. Trust us, you will get numerous delivery orders to boost your earnings.', des2: 'As retailers, If you want to increase your sales, we are for you. Handover has delivery executives who would deliver maximum goods to your customers in a day. Delivery champs earn money from per delivery they do, not directly from you as fixed salary. So join us ASAP. If you have something to say about our services, please do so. We will entertain your thoughts.', heading2: 'Exploring Thane', subheading2: 'Let’s Check Out Thane and Its Specialties', des3: 'Thane city falls in the state of Maharashtra and has a rich cultural heritage. There are many historians who often quote the city in their writing – Greek geographer Ptolemy, Marco Polo, Ibn Batuta, Duarte Barbosa, etc. In India, the first ever rail train was started from Boribunder to Thane which played a vital role in shaping the future of the city. Today, Thane has evolved as the centre for trade and construction activities due to its proximity to Mumbai. Besides, you will enjoy witnessing beautiful lakes in the city.', population: ' 25.3 lakh (approx.)', popularsites: ' Butterfly Park, Upvan Lake, Korum Mall, etc.' },
    { location: "mumbai",map_url: "https://www.google.com/maps/place/Mumbai,+Maharashtra/@19.082502,72.7163725,11z/data=!3m1!4b1!4m6!3m5!1s0x3be7c6306644edc1:0x5da4ed8f8d648c69!8m2!3d19.0759837!4d72.8776559!16zL20vMDR2bXA?entry=ttu", location_name: "Delivery Services in Mumbai", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Mumbai.', des1: 'If you are looking for a delivery jobs in Mumbai, we are here to support you. Handover creates such job opportunities for people in the city. Get registered with Handover and start picking products from retailers and delivering the same to their customers.', des2: 'As retailers, you need not keep a delivery executive on a fixed salary. Handover will provide you with delivery executives on a pay per delivery basis. It will motivate them to do more delivery and increase your sales. We will appreciate your feedback for our delivery services.', heading2: 'Exploring Mumbai', subheading2: 'Let’s Check Out Mumbai and Its Specialties', des3: 'Mumbai is the financial capital of India, and one of the most populated cities in the country. The city exhibits the blend of iconic old world charm architecture and cultural and traditional structures all around. Apart from these, Mumbai is the home of Bollywood where several stalwart actors/actresses live. People across the country come to the city to enter Bollywood. Overall, Mumbai accepts people from all backgrounds.', population: '1.71 crore (approx.)', popularsites: ' Gateway of India, Juhu Beach, Haji Ali, Taj Hotel, etc.' },
    { location: "navi-mumbai",map_url: "https://www.google.com/maps/place/Navi+Mumbai,+Maharashtra/@19.0166036,72.8683475,11z/data=!3m1!4b1!4m6!3m5!1s0x3be7b9f0b81f13ad:0x3c12f7681185f869!8m2!3d19.0330488!4d73.0296625!16zL20vMDNqejB6?entry=ttu", location_name: "Delivery Services in Navi Mumbai", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More.', des1: 'If you are searching for a food delivery jobs, grocery delivery jobs and other delivery jobs in Navi Mumbai, we’ve heard you! Handover lets you earn your livelihood by delivering goods to the customers.', des2: 'As retailers, you may feel burdened by paying a fixed salary to your delivery executive regardless of their delivery performance. Handover provides you with suitable people who will pick up the products from your shop and deliver them to your customers without any fixed cost. These delivery executives earn money on deliveries made by them. Please use our services and comment on it. We will appreciate your feedback for our delivery services.', heading2: 'Exploring Navi Mumbai', subheading2: 'Let’s Check Out Navi Mumbai and Its Specialties', des3: 'To escape the prolonged Mumbai traffic and overpopulation of the city in early 1970, Navi Mumbai was designed to develop. The city is considered the world’s largest planned metro city consisting of industries and robust infrastructure. If we compare the accommodation cost of Navi Mumbai with Mumbai, the former is far cheaper and more planned. Furthermore, the city offers job opportunities and recreational spaces.', population: ' 14 lakh (approx.)', popularsites: 'Central park, Pandavkada Falls, Karnala Bird Sanctuary, Rock Garden, etc.' },
    { location: "nashik",map_url: "https://www.google.com/maps/place/Nashik,+Maharashtra/@19.9911053,73.7210787,12z/data=!3m1!4b1!4m6!3m5!1s0x3bddd290b09914b3:0xcb07845d9d28215c!8m2!3d19.9974533!4d73.7898023!16zL20vMDM3dmtr?entry=ttu", location_name: "Delivery Services in Nashik", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More.', des1: 'If you are searching for food delivery jobs, grocery delivery jobs and other delivery jobs in Nashik, Handover offers you the same. Get started with Handover and earn your livelihood by delivering goods to many customers in the city.', des2: 'As retailers, if you are annoyed by paying a fixed salary to your delivery executives, Handover eases your pain. We provide you with people who pick up the goods from your shops and deliver them to your customers. Delivery champs earn basis the delivery they do. So, use our delivery services and comment on the same. We’ll appreciate your feedback and keep solving your delivery issues.', heading2: 'As retailers, if you are annoyed by paying a fixed salary to your delivery executives, Handover eases your pain. We provide you with people who pick up the goods from your shops and deliver them to your customers. Delivery champs earn basis the delivery they do. So, use our delivery services and comment on the same. We’ll appreciate your feedback and keep solving your delivery issues.', subheading2: 'Let’s Check Out Nashik and Its Specialties', des3: 'Nashik is also known as the wine capital of India due to the abundance of vineyards existing in the city. The city is one of the seven sites which hosts ‘Kumbh Mela’ every 12 years. Furthermore, Nashik accounts for a large share of fruits and vegetables’ production in the country. If we talk about education, the city has been upgrading itself as the education hub of Maharashtra. The architectural  development of the city is a blend of ancient and modern touch.', population: '2 million (approx.)', popularsites: ' Pandavleni Caves, Sula Vineyard, Saptasharungi, Anjneri Hill, etc.' },
    { location: "aurangabad",map_url: "https://www.google.com/maps/place/Aurangabad,+Maharashtra/@19.8702388,75.2227993,12z/data=!3m1!4b1!4m6!3m5!1s0x3bdb9815a369bc63:0x712d538b29a2a73e!8m2!3d19.8761653!4d75.3433139!16zL20vMDJucGs1?entry=ttu", location_name: "Delivery Services in Aurangabad", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Aurangabad.', des1: 'Handover is looking for people who have been waiting to get a delivery job. We are in your city i.e. Aurangabad. Join us and start earning your livelihood. Owners of shops, restaurants and other business outlets in the city want people to deliver groceries, milk and various other stuff to their customers. The more you deliver, the more you will earn.', des2: 'Whereas if you are a business owner, you might be feeling burdened by paying a fixed salary to your delivery executives. Handover provides you with delivery champs who will pick up goods from you and deliver them to your customers on a pay per delivery model. No fixed salary! So, contact us, take our delivery services, and have your say on the same. We will appreciate your comments.', heading2: 'Exploring Aurangabad', subheading2: 'Let’s Check Out Aurangabad and Its Specialties', des3: 'Aurangabad is encompassed with several beautiful and legendary monuments including the famous UNESCO world heritage sites Ajanta and Ellora caves. Aurangabad was named after Mughal emperor Aurangzeb, after the Mughal got control of the city in 1653. The city is rich in its history where one can see the ‘Bibi Ka Maqbara’, a famous resemblance of Taj Mahal. Presently, Aurangabad is one of the leading producers of silk fabric shawls. Besides, it is an educational hub, having Dr. Babasaheb Ambedkar Marathwada University and several other educational centers.', population: '1.6 million (approx.)', popularsites: 'Ajanta and Ellora Caves, Bibi ka Maqbara, Daulatabad Fort, Salim Ali Lake, etc.' },
    { location: "pune",map_url: "https://www.google.com/maps/place/Pune,+Maharashtra/@18.5248706,73.6981537,11z/data=!3m1!4b1!4m6!3m5!1s0x3bc2bf2e67461101:0x828d43bf9d9ee343!8m2!3d18.5204303!4d73.8567437!16zL20vMDE1eTJx?entry=ttu", location_name: "Delivery Services in Pune", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Pune.', des1: 'Are you still waiting to get a delivery jobs in Pune? Then its ok! Handover is in Pune and wants to hire you for the same. So, dont miss the chance and earn your livelihood by joining us.', des2: 'For businesses, every passing month adds too much to their delivery cost. They have to pay their delivery executives no matter what. Because these executives mostly work on a fixed salary. Handover reduces the cost by providing businesses with delivery executives on a variable pay model. In simple terms, the payment happens only on delivery. Handover’s delivery executives will deliver the goods to customers. So, join Handover, avail of its services and give your kind feedback on the same. We will appreciate your feedback and respond positively.', heading2: 'Exploring Pune', subheading2: 'Let’s Check Out Pune and Its Specialties', des3: 'Pune is the second largest city in the state of Maharashtra after Mumbai. The city plays an important role in the state’s economy due to many companies operating from here. In the past, Pune was the hometown and centre power of the Maratha empire. There are numerous edifices in the city, illustrating its glorious past. Besides, Pune has established itself as the leading center for education and earned the nickname ‘Oxford of East.', population: '4.3 million (approx.)', popularsites: 'Darshan Museum, ISKCON NVCC Temple, Sinhagad Fort, Sri Balaji Mandir, etc.' },
    { location: "cuttack",map_url: "https://www.google.com/maps/place/Cuttack,+Odisha/@20.4632488,85.7853438,12z/data=!3m1!4b1!4m6!3m5!1s0x3a190d832223af81:0x22f5fa1c913be52e!8m2!3d20.462521!4d85.8829895!16zL20vMDV3MGtu?entry=ttu", location_name: "Delivery Services in Cuttack", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Cuttack.', des1: 'Are you facing challenges in getting a delivery jobs in Cuttack? Now, you dont have to worry any more. Handover gives you that job, so connect with us. We are providing you with job opportunities so that you can earn money by delivering goods.', des2: 'As retailers, you must not be feeling good paying a fixed salary to your delivery executive. You can get rid of it by taking the services from handover. Handover provides delivery champs who don’t take the fixed monthly salary rather earn on each delivery they do to customers. We will be happy to have you on board!  Do collaborate with us.', heading2: 'Exploring Cuttack', subheading2: 'Let’s Check Out Cuttack and Its Specialties', des3: 'Cuttack is the former capital and second largest city of the Indian state of Odisha. It is also known as the Millennium City as well as the Silver City due to its history of 1000 years and famous silver filigree works. The city is called the commercial capital of Odisha having many trading and business activities. It also has good rail and road connection to the rest of Odisha, West Bengal and other cities. As far as education is concerned, Cuttack has several reputed colleges such as The Central Rice Research Institute, and the Odisha School of Engineering, etc. Apart from these, the city is birthplace of great Indian freedom fighter Netaji Subhas Chandra Bose.', population: '8.4 lakh (approx)', popularsites: 'Barabati Kataka Fort, Netaji Birth Place Museum, Dhabaleswar Island, etc.' },
    { location: "puri",map_url: "https://www.google.com/maps/place/Puri,+Odisha/@19.8089024,85.7804001,13z/data=!3m1!4b1!4m6!3m5!1s0x3a19c4180256e495:0x496a9d8b30c1fad7!8m2!3d19.8134554!4d85.8312359!16zL20vMDR0cTUy?entry=ttu", location_name: "Delivery Services in Puri", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Puri.', des1: 'If you are searching for a delivery executive job in Puri, Handover is in your city ready to provide you the same. You can earn your livelihood by connecting with us. You can do food delivery, grocery delivery job, milk delivery job and related work and earn.', des2: 'As retailers, paying a fixed salary to your delivery executive must be a burden for you. So handover comes with an idea which is likely to reduce your financial burden. We have delivery executives who pick up the goods from your shop and deliver them to your customers in Puri. The money you pay to these executives will depend on how many deliveries they do, eliminating the scope for a fixed monthly payment. So, contact us and take our services. We will appreciate your response!', heading2: 'Exploring Puri', subheading2: 'Let’s Check Out Puri and Its Specialties', des3: 'Puri is the city in Odisha and is also the spiritual capital of the state. The city is quite famous for its temples, shrines, mathas, shrams, natural wonders, beaches, architectural splendor, which garner the attention of the tourists from around the world. According to Hindu mythology, Jagannath in Puri is one of the four sacred dhams. Besides, beaches like Swargadwar beach and Puri beach in Puri are the main attractions for tourists.', population: ' 2.75 lakh (approx.)', popularsites: 'Jagannath temple, Puri Beach, Raghurajpur artist village, Chilika lake, etc.' },
    { location: "ludhiana",map_url: "https://www.google.com/maps/place/Ludhiana,+Punjab/@30.9004664,75.7742715,12z/data=!3m1!4b1!4m6!3m5!1s0x391a837462345a7d:0x681102348ec60610!8m2!3d30.900965!4d75.8572758!16zL20vMDJjN3Ri?entry=ttu", location_name: "Delivery Services in Ludhiana", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Ludhiana.', des1: 'Hi everyone! If you are looking for a delivery executive job in Ludhiana, contact Handover today. We create job opportunities for those who wish to earn their livelihood by delivering goods to customers.', des2: 'As a business owner, if you contact handover for delivery services, you would not need to pay the salary to a delivery executive every month. We provide delivery executives who earn based on the delivery they do from your shop to your customers. So, you can take our services and have your say on it. We’ll serve you even better.', heading2: 'Exploring Ludhiana', subheading2: 'Let’s Check Out Ludhiana and Its Specialties', des3: 'Ludhiana is a city in Punjab and its name was derived from the Lodhi Dynasty which founded the city in 1480. The city touches the Grand Trunk Road stretching from Delhi to Amritsar. The city’s economy mostly depends on hosiery manufacturing, the production of cotton textiles, steel, machinery and agricultural products. As far as education is concerned, Ludhiana has the Punjab Agricultural University (founded in 1962) and several other colleges.', population: '2.2 million ( approx.)', popularsites: 'Lodhi Fort, Maharaja Ranjit Singh War Museum, Pavillion Mall, Rakh Bagh Park, etc.' },
    { location: "jaipur",map_url: "https://www.google.com/maps/place/Jaipur,+Rajasthan/@26.8854214,75.6257451,11z/data=!3m1!4b1!4m6!3m5!1s0x396c4adf4c57e281:0xce1c63a0cf22e09!8m2!3d26.9124336!4d75.7872709!16zL20vMDE2NzIy?entry=ttu", location_name: "Delivery Services in Jaipur", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Jaipur.', des1: 'Are you still looking for a delivery jobs in Jaipur? Then its ok! Handover is in Jaipur and wants to hire you for the same. So, dont miss the chance and earn your livelihood by joining us.', des2: 'While businesses are doing good, their delivery cost hasn’t been under control due to a fixed salary they pay to their executives. It means you have to pay your delivery executives no matter whether your goods are being sold or not. Handover reduces your cost by providing delivery executives on payment per delivery model in Jaipur.  In simple terms, the payment happens only on delivery. Handover’s delivery executives will deliver the goods to customers. So, join Handover, take advantage of its services and give us your valuable feedback on the same.', heading2: 'Exploring Jaipur', subheading2: 'Let’s Check Out Jaipur and Its Specialties', des3: 'Being the most populous city of Rajasthan, Jaipur is a walled city surrounded (except to the South) by hills. It is said that the city was founded in 1727 by Maharaja Sawai Jai Singh to replace nearby Amber as the capital of the princely state of Jaipur. The city has the harmonious existence of both Hindu and Muslim since ages. Jaipur is the home to various heritage monuments such as Hawa Mahal, Nahargarh Fort, illustrating the city’s beauty. There are several reputed universities and colleges in the city, like Jaipur National University, Manipal University, ICFAI University, etc. All these institutes make Jaipur a good destination for students.', population: '4.5 million (approx.)', popularsites: 'Hawa Mahal, Jantar Mantar, Sheesh Mahal, etc.' },
    { location: "hyderabad",map_url: "https://www.google.com/maps/place/Hyderabad,+Telangana/@17.4126086,78.2432317,11z/data=!3m1!4b1!4m6!3m5!1s0x3bcb99daeaebd2c7:0xae93b78392bafbc2!8m2!3d17.385044!4d78.486671!16zL20vMDljNnc?entry=ttu", location_name: "Delivery Services in Hyderabad", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Hyderabad.', des1: 'Hello! Hyderabad, Handover is in your city. And we are looking for people who are ready to work as delivery champs. We create job opportunities for them who want to earn their livelihood by delivering products to customers. So connect with Handover, pick your delivery from retailers and deliver them to their customers.', des2: 'As retailers, paying a fixed salary to your delivery executive must be annoying you, and you might want to come out of these circumstances, but have failed to do so. So, Handover comes to solve your problems. We provide the shopkeepers with delivery champs who earn by delivering orders to customers. No fixed salary. So do take our services and give us your feedback. We’ll consider your thoughts.', heading2: 'Exploring Hyderabad', subheading2: 'Let’s Check Out Hyderabad and Its Specialties', des3: 'Hyderabad is Telangana’s largest and most-populous city and is the major urban centre for all of south-central interior India. From 1956 to 2014, Hyderabad was the capital of Andhra Pradesh state, but with the creation of Telangana from Andhra Pradesh in 2014, it became the capital of both states. The city is recognised as a hub of trade and commerce and an international centre for information technology (IT) across the world. Besides, pharmaceuticals, cigarettes and textiles are the major products manufactured in the city. The city has long been associated with Telugu-language films, like Mumbai is for Bollywood, so Hyderabad is famous for Tollywood.', population: '9.2 million (approx.)', popularsites: 'Charminar, Golconda Fort, Ramoji Film City, etc.' },
    { location: "lucknow",map_url: "https://www.google.com/maps/place/Lucknow,+Uttar+Pradesh/@26.8489028,80.7777,11z/data=!3m1!4b1!4m6!3m5!1s0x399bfd991f32b16b:0x93ccba8909978be7!8m2!3d26.8466937!4d80.946166!16zL20vMDIydHE0?entry=ttu", location_name: "Delivery Services in Lucknow", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Lucknow.', des1: 'Many youngsters in Lucknow may be looking for food delivery jobs, grocery delivery jobs and other delivery jobs. You need not to worry because Handover is in your city to provide you with the same job. So, get started with Handover and earn your livelihood by delivering goods to many customers in the city.', des2: 'Whereas as business owners, you would no longer need to keep delivery executives on a monthly salary. You can thus enjoy lots of savings. Handover provides you delivery champs who pick up goods from your shop and deliver to your customers in Lucknow. They will receive money based on the delivery they do. Take our services and give us your feedback.', heading2: 'Exploring Lucknow', subheading2: 'Let’s Check Out Lucknow and Its Specialties', des3: 'Lucknow’s significance dates back to the 16th century, when Mughal’s first emperor Babur captured the city in 1528. But now it is the capital of Uttar Pradesh state. The city is famous for agricultural products such as mangoes, melons, and various grains, etc.  And its industries include food processing, manufacturing, handicrafts, and railroad shops. Lucknow has established itself as the top educational hub of the country, having several universities and colleges such as University of Lucknow (founded 1921), a music academy, an institute of Muslim theology, the Central Drug Research Institute (1951), an arts-and-crafts college, and a state museum.', population: ' 3.8 million ( approx.)', popularsites: ' Bara Imambara, Rumi Darwaza, Ambedkar Memorial Park, etc.' },
    { location: "kanpur",map_url: "https://www.google.com/maps/place/Kanpur,+Uttar+Pradesh/@26.4473038,80.2559808,12z/data=!3m1!4b1!4m6!3m5!1s0x399c4770b127c46f:0x1778302a9fbe7b41!8m2!3d26.449923!4d80.3318736!16zL20vMDFfcTdo?entry=ttu", location_name: "Delivery Services in Kanpur", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Kanpur.', des1: 'If you are looking for delivery jobs in Kanpur, Handover is in your city to provide the same. We create job opportunities for the people of Kanpur so that they can earn their livelihood by working with us. So, join us ASAP and start working.', des2: 'As retailers, if you feel burdened paying a fixed salary to your delivery executives, we are for you! Now, Handover comes with an idea which could reduce your burden. We provide delivery champs who pick up the order from you and deliver them to your customers. These champs earn per deliveries. Join us now.', heading2: 'Exploring Kanpur', subheading2: 'Let’s Check Out Kanpur and Its Specialties', des3: 'Kanpur is the industrial centre of India, and it is also considered the economic capital of India. Kanpur has several tanneries that make it the leather capital of India. These were the economical aspects of the city, when we see the city culturally, it held numerous fairs throughout the years which are understood to be the paradigm of cultural ethos. And one of the most important fairs held in Kanpur is Ganga Mela after Holi every year for five days. Participants in fairs usually throw the colours on each other and later bath in river Ganga.', population: ' 3.8 million (approx.)', popularsites: 'Green Park Stadium, Kanpur Zoological Park, Kanpur Memorial Church, etc.' },
    { location: "allahabad",map_url: "https://www.google.com/maps/place/Prayagraj,+Uttar+Pradesh/@25.4024821,81.6367716,11z/data=!3m1!4b1!4m6!3m5!1s0x398534c9b20bd49f:0xa2237856ad4041a!8m2!3d25.4358011!4d81.846311!16zL20vMDIwc2tj?entry=ttu", location_name: "Delivery Services in Allahabad (officially known as Prayagraj)", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Allahabad.', des1: 'Hello! Allahabad, Handover gives delivery jobs to many youngsters in the city. So, dont miss the chance and earn your livelihood by joining us.', des2: 'As retailers, you must be anxious about paying a fixed salary to your delivery executives. Handover understands your pain and has thus given you an opportunity to serve you on pay per delivery model. According to this model, we will provide you with people who pick up the items and deliver them to your customers. You will need to pay them based on their delivery volumes. Let’s join us, use our services and give your feedback.', heading2: 'Exploring Allahabad (Prayagraj)', subheading2: 'Let’s Check Out Allahabad (Prayagraj) and Its Specialties', des3: 'Allahabad is one of the largest cities of Uttar Pradesh and is also one of the historical and mythological cities of the country with glorious past and present. Despite being the centre of Hindu religious pilgrimage, the city has a mixed culture of Hindu, Muslims, Jains and Christians. Allahabad is also considered as the judicial capital of Uttar Pradesh, due to the highest number of state courts existing in the city. As far as education is concerned, the city has a number of universities and colleges, like Indian Institute of Information Technology ( IIIT ), Motilal Nehru Regional Engineering College MNREC, Medical and Agriculture College, etc.', population: '1.5 million (approx.)', popularsites: 'Khusro Bagh, Akbar Fort, Anand Bhawan, etc.' },
    { location: "varanasi",map_url: "https://www.google.com/maps/place/Varanasi,+Uttar+Pradesh/@25.3208949,82.908707,12z/data=!3m1!4b1!4m6!3m5!1s0x398e2db76febcf4d:0x68131710853ff0b5!8m2!3d25.3176452!4d82.9739144!16zL20vMDFqOTIy?entry=ttu", location_name: "Delivery Services in Varanasi (Banaras)", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Varanasi.', des1: 'If you are looking for delivery jobs in Varanasi, connect with Handover today! We are providing job opportunities in your city so that you can earn by delivering goods. You will need to pick up products from retailers and deliver them to their customers.', des2: 'As retailers, you don’t need to continue with delivery executives on a fixed salary basis. This will surely reduce your burden. Handover provides you delivery champs who will pick up goods from you and deliver them to your customers. And the best part is that these champs receive money on the basis of every delivery they do. As a result, it motivates them to do more deliveries and boost your sales. Connect with Handover ASAP. We will appreciate the same!', heading2: 'Exploring Varanasi (Banaras)', subheading2: 'Let’s Check Out Varanasi (Banaras) and Its Specialties', des3: 'Varanasi is the city of Uttar Pradesh and is located on the bank of Ganga river and is one of the seven sacred cities of Hinduism.The city has several schools and Brahman pandits (learned scholars. Besides, the city is a centre of arts, crafts, music and dance and is also famous for its silks and brocades with gold and silver thread work.', population: '1.1 million (approx.)', popularsites: ' Assi Ghat, Kashi Vishwanath Temple, Ramnagar Fort, etc.' },
    { location: "midnapore",map_url: "https://www.google.com/maps/place/Midnapore,+West+Bengal/@22.4308148,87.2773636,13z/data=!3m1!4b1!4m6!3m5!1s0x3a1d5b398c19fb15:0x5e88bcfa42e549cd!8m2!3d22.4256613!4d87.3198819!16zL20vMDY1eV92?entry=ttu", location_name: "Delivery Services in Midnapore", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Midnapore.', des1: 'Hello! Guys, are you searching for a food delivery jobs, grocery delivery jobs and other delivery jobs in Midnapore? Handover is there to help you. We create job opportunities for youngsters who are willing to earn their livelihood by delivering goods.', des2: 'As retailers, Handover is by which you can increase your sales. But how?? We provide you with delivery champs who deliver the ordered products to customers without charging you directly. They earn based on the delivery they do. You no longer need to keep a delivery executive on a monthly salary.  Take our services and give us your feedback.', heading2: 'Exploring Midnapore', subheading2: 'Let’s Check Out Midnapore and Its Specialties', des3: 'Midnapore is a city in West Bengal, and It is situated on the banks of the Kangsabati River. In ancient times the region seems to be highly influenced by Jainism and Buddhism.  Midnapore reserves the numbers of prehistoric sites which are of interest to archaeologists. Furthermore, the city celebrates festivals with much fanfare. On one hand, Urs of the revered Maulana Syed Shah Murshed Ali al Qadri Pir Saheb is a major occasion for Muslim of the city. On the other hand, Rathayatra and Durga puja are celebrated by Hindus. For education, Midnapore has several universities and colleges such as Midnapore College, Midnapore Law College, etc.', population: '2.26 lakh (approx.)', popularsites: 'Digha Beach, Kanak Durga Temple, Gopegarh Eco Park, etc.' },
    { location: "kharagpur",map_url: "https://www.google.com/maps/place/Kharagpur,+West+Bengal/@22.3309041,87.262499,12z/data=!3m1!4b1!4m6!3m5!1s0x3a1d44143b5c99a1:0xf37ae5b844180ec4!8m2!3d22.34601!4d87.2319753!16zL20vMDQ3MHpn?entry=ttu", location_name: "Delivery Services in Kharagpur", heading1: '#1 Choice for All Your Delivery Needs – Food Delivery, Grocery Delivery & More in Kharagpur.', des1: 'Hello! Kharagpur, are you looking for a food delivery jobs, Grocery Delivery Jobs and other delivery jobs in Kharagpur? Handover is there to support you. You can be our next delivery champ and can earn money by picking goods from retailers and delivering them to their customers.', des2: 'As retailers, you need not keep a delivery executive on a fixed salary. Subsequently, you can save a huge amount of money.  Handover will provide you with delivery executives on a pay per delivery basis. It will motivate them to do more deliveries and increase your sales. We will appreciate your feedback for our delivery services.', heading2: 'Exploring Kharagpur', subheading2: 'Let’s Check Out Kharagpur and Its Specialties', des3: 'Kharagpur is a city of West Bengal, and It is an important industrial, commercial and educational centre. Kharagpur is considered a cosmopolitan city, and known for its multiculturalism and diversity. People across the religions, castes and communities live here together in peace and harmony. Bengali, English, Hindi, Telugu are the languages widely spoken among the people in Kharagpur. Besides, the city is widely known for its quality education. There are several reputed universities and colleges such as Indian Institute of Technology (IIT), Property Rajiv Gandhi School Of Intellectual Law, etc.', population: ' 2.85 lakh (approx.)', popularsites: 'Nehru Museum of Science and Technology, Lake Park, Kharagpur Railway Platform, etc.' }

]
